comercio_electronico/comercio_electronico/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
 #   path('usuario/'. include('usuario.urls')),
    path('', views.index, name= 'index'),
    path('productos/', include('productos.urls')),
    path('usuarios/', include('usuario.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comercio_electronico/productos/urls.py
from django.urls import path, include
from . import views

app_name = "productos"
urlpatterns = [
    path('filtro_categoria/<int:id>', views.filtro_categoria, name="filtro_categoria"),
    path('crear_producto/', views.crear_producto, name="crear_producto"),
    path("<int:id>/borrar", views.borrarProducto, name="borrarProducto"),
    path("editar_producto/<int:id>", views.editar_producto, name="editar_producto"),
    path('carrito', views.carrito, name="carrito"),
    path('carrito/<int:id>/agregarCarrito', views.agregarCarrito, name="agregarCarrito"),
    path("<int:id>/borrar_carrito", views.borrar_carrito, name="borrar_carrito"),
    path("<int:id>/editar_carrito", views.editar_carrito, name="editar_carrito"),
    path("search", views.search, name="search"),
    path('agregar_categoria/', views.agregar_categoria, name="agregar_categoria"),
    path("editar_categoria/<int:id>", views.editar_categoria, name="editar_categoria"),
    path("<int:id>/borrar_categoria", views.borrar_categoria, name="borrar_categoria"),
]

comercio_electronico/usuario/urls.py
from django.urls import path, include
from . import views

app_name = "usuarios"
urlpatterns = [
    path("cerrarSesion", views.cerrarSesion, name="cerrarSesion"),
]

comercio_electronico/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>MrBots {{ title }}</title>
	<!--css Jorge--->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css"
		integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/normalize.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="body">
{% block body %}

{% endblock %}
	<!--scripts de Jorge-->
	<script src="{% static 'js/app.js' %}"></script>
</body>
</html>

comercio_electronico/templates/carousel.html
{% load static %}
<section class="hero">
	<div class="contenedor">
		<div class="hero__informacion">
			<div class="boton atras" onclick="atras();">
			<i class="fas fa-chevron-left"></i>
		</div>
		
		<div class="boton siguiente" onclick="siguiente();">
			<i class="fas fa-chevron-right"></i>
		</div>
		<div class="img">
		</div>
		</div>
		
	</div>
</section>
<script>	
let imagenes=new Array("{% static 'img/mercado1.png' %}", "{% static 'img/mercado2.png' %}", "{% static 'img/mercado3.png' %}", "{% static 'img/mercado4.png' %}");
let posicion = 0;
let img = document.querySelector('.img');
img.style.backgroundImage='url('+imagenes[posicion]+')';

function atras(){
	if(posicion == 0){
		posicion=3;
	} else{
		posicion--;
	}
	img.style.backgroundImage='url('+imagenes[posicion]+')';
}	

function siguiente(){
	if(posicion == 3){
		posicion=0;
	} else{
		posicion++;
	}
	img.style.backgroundImage='url('+imagenes[posicion]+')';
}	

setInterval(function(){
	siguiente();
}, 9000);
</script>

comercio_electronico/templates/footer.html
<footer class="footer">
	<div class="contenedor">
		<section class="contacto">
			<h3 class="footer__contacto">Contacto</h3>
			<div class="contacto__informacion">
				<span class="contacto__direccion contacto__item"><i class="fas fa-map-marker-alt"></i>Uruguay 490, Gral. José de San Martín, Chaco</span>
			    <span class="contacto__email contacto__item"><i class="fas fa-envelope-open-text"></i>ejemplo@ejemplo.com</span>
			    <span class="contacto__tel contacto__item"><i class="fas fa-headset"></i>(+54) 123-456-789</span>
			</div>
		</section>
		<section class="copy">
			<p class="copy__nombre">Copyright &copy; 2021 Mr Bot</p>
		</section>
		<div class="metodos-pago">
			<span class="maestro tarjeta"></span>
			<span class="mastercard tarjeta"></span>
			<span class="visa tarjeta"></span>
		</div>
	</div>
</footer>

comercio_electronico/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<!--bootstrap 5-->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<script src="https://kit.fontawesome.com/1356b06277.js" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<body>	
	<div class="mensaje-publicitario">
		<h3 class="mensaje-publicitario__titulo centrar-text">La mejor tienda de Gral. San Martín</h3>
	</div>

	{% include 'navbar.html' %}
	
	{% include 'carousel.html' %}

	{% block content %}
	{% endblock %}
	</section>
	<main class="compras">
		<div class="contenedor">
			<section class="productos">
				<h1 class="productos__titulo">Ofertas Imperdibles</h1>
				{% if categoria_seleccionada %}
        		<div class="alert alert-info" role="alert">{{ categoria_seleccionada }}</div>
   				{% else %}
       			<div class="alert alert-info" role="alert">Todos los Productos</div>
    			{% endif %}
				<section class="productos__entradas">
				{% include 'productos/card_productos.html' with lista_productos=lista_productos %}
				</section>
			</section>
		</div>
	</main>

<!---paginate--->
	<nav aria-label="Page navigation example">
	  {% if page_obj.has_next or page_obj.has_previous %}
	    <ul class="paginacion">
	    {% if page_obj.has_previous %}
		    <li class="paginacion__items formulario__btn"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">Anterior</a>
			</li>
		{% endif %}
		{% for page in page_obj.paginator.page_range %}
		    <li class=" paginacion__items formulario__btn {% if page_obj.number == page %}active{% endif %}"><a class="page-link" href="?page={{ page }}">{{ page }}</a>
		    </li>
		{% endfor %}
		{% if page_obj.has_next %}
		    <li class="paginacion__items formulario__btn"><a href="?page={{ page_obj.next_page_number }}" class="page-link">Siguiente</a>
		    </li>
		{% endif %}
		</ul>
	  {% endif %}
	</nav>
</div>

<!--	<div class="container">	
		<div class="row" >
		{% block contenido %}

		{% endblock %}
		</div>
	</div>
	<br><br>
</div>--->
	
	{% include 'footer.html' %}
</body>

{% endblock %}

comercio_electronico/templates/navbar.html
{% load static %}
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css"
		integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/normalize.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

<header class="header-principal">
		<div class="contenedor">
			<div class="barrar-header">
				<div class="search-user-menu flex-h-v">
					<a href="{% url 'index' %}" class="logo">
						<img src="{% static 'img/logotipo.png' %}" alt="logotipo">
					</a>
					{% include "productos/search_form.html"%}
					<div class="carrito">
						<a href="{% url 'productos:carrito' %}" class="carrito__icon"><i class="fas fa-shopping-cart"></i></a>
						<!-- <span class="carrito__producto flex-h-v">0</span> -->
						<i class="fas fa-user carrito__usuario"></i>
					</div>
					<i class="fas fa-bars menu-principal__open"></i>
				</div>
			</div>
		</div>
		<section class="usuario">
			<div class="contenedor">
				{% if request.user.is_authenticated %}
				<a class="formulario__btn" href="{% url 'usuarios:cerrarSesion' %}">Cerrar Sesion</a>
				{% else %}
				<form class="formulario" method="POST">
					{% csrf_token %}
					<h3 class="usuario__titulo">Crear Cuenta</h3>	
					{% for x in forms %}				
      					{{ x }}
      					{{ x.errors }}
      				{% endfor %}      				
					<input class="formulario__btn" type="submit" value="Registrarme">					
				</form>
				{% endif %}
			</div>
		</section>
		<nav class="menu-principal">
			<ul class="menu">
				<li class="menu__items"><a class="menu__link" href="{% url 'index' %}">Inicio</a></li>
				<li class="menu__items"><a class="menu__link" href="#">Ofertas</a></li>
				<li class="menu__items item-submenu"><a class="menu__link subcategoria" href="#"><i class="fas fa-caret-down submenu__icon"></i>Categorias</a>
				<ul class="submenu">
					<li class="submenu__items">
						{% for categoria in lista_categorias %}
						<a class="submenu__link" href="{% url 'productos:filtro_categoria' categoria.id%}">
						{{ categoria }}
						</a>
						{% endfor %}
					</li>
				</ul>
				</li>
				<li class="menu__items"><a class="menu__link" href="{% url 'productos:crear_producto' %}">Agregar Producto</a></li>
				<li class="menu__items"><a class="menu__link" href="{% url 'productos:agregar_categoria' %}">Crear categorias</a></li>
				<i class="fas fa-times menu-principal__close"></i>
			</ul>
		</nav>
	</header>

<script src="{% static 'js/app.js' %}"></script>