comercio_electronico/comercio_electronico/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
 #   path('usuario/'. include('usuario.urls')),
    path('', views.index, name= 'index'),
    path('productos/', include('productos.urls')),
    path('usuarios/', include('usuario.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comercio_electronico/productos/urls.py
from django.urls import path, include
from . import views

app_name = "productos"
urlpatterns = [
    path('filtro_categoria/<int:id>', views.filtro_categoria, name="filtro_categoria"),
    path('crear_producto/', views.crear_producto, name="crear_producto"),
    path("<int:id>/borrar", views.borrarProducto, name="borrarProducto"),
    path("editar_producto/<int:id>", views.editar_producto, name="editar_producto"),
    path('carrito', views.carrito, name="carrito"),
    path('carrito/<int:id>/agregarCarrito', views.agregarCarrito, name="agregarCarrito"),
    path("<int:id>/borrar_carrito", views.borrar_carrito, name="borrar_carrito"),
    path("<int:id>/editar_carrito", views.editar_carrito, name="editar_carrito"),
    path("search", views.search, name="search"),
    path('agregar_categoria/', views.agregar_categoria, name="agregar_categoria"),
    path("editar_categoria/<int:id>", views.editar_categoria, name="editar_categoria"),
    path("<int:id>/borrar_categoria", views.borrar_categoria, name="borrar_categoria"),
]

comercio_electronico/usuario/urls.py
from django.urls import path, include
from . import views

app_name = "usuarios"
urlpatterns = [
    path("cerrarSesion", views.cerrarSesion, name="cerrarSesion"),
]

comercio_electronico/productos/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User
from usuario.models import Perfil

class Categorias(models.Model):
    categoria = models.CharField(max_length=64, null=False)

    def __str__(self):
        return f"{self.categoria}"


class Productos(models.Model):
	categoria = models.ForeignKey(Categorias, on_delete=models.CASCADE, related_name="clasificacion_seccion")
	fecha_creacion = models.DateTimeField(auto_now_add=True)
	titulo = models.CharField(max_length=250, null=False)
	contenido = models.CharField(max_length=2000, null=False)
	imagen = models.ImageField(upload_to="productos", null=True, blank=True)
	precio = models.CharField(max_length=10, default=0)
	precio_oferta = models.CharField(max_length=10, default=0)
	usuario = models.ForeignKey(Perfil, on_delete=models.CASCADE, related_name="usuario")
	productos_disponibles = models.BooleanField(default = True)

	def __str__(self):
		return f"{self.fecha_creacion} - {self.titulo} - ${self.precio} ({self.usuario})"


class Carritos(models.Model):
	usuario =  models.ForeignKey(Perfil, on_delete = models.SET_NULL, null = True)
	producto = models.ForeignKey(Productos, null=True, blank=True, on_delete=models.CASCADE)
	fecha_creacion = models.DateTimeField(auto_now_add=True)
	cantidad = models.CharField(default=1, max_length=3)


	def __str__(self):
		return f"{self.producto} - ({self.usuario})"

comercio_electronico/productos/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm

from django.contrib.auth.models import User
from .models import Productos, Carritos, Categorias

class ProductosForm(forms.ModelForm):
    class Meta:
        model = Productos
        fields = "__all__"
        exclude = ('usuario',)

    def __init__(self, *args, **kwargs):
        super(ProductosForm, self).__init__(*args, **kwargs)
        self.fields["categoria"].widget.attrs.update({'class': 'campo__input', 'type':"text", 'placeholder':"elija la categoria"})
        self.fields["titulo"].widget.attrs.update({'class': 'campo__input', 'type':"text", 'placeholder':"Nombre del producto"})
        self.fields["precio"].widget.attrs.update({'class': 'campo__input', 'type':"text", 'placeholder':"precio del producto"})
        self.fields["precio_oferta"].widget.attrs.update({'class': 'campo__input', 'type':"text",})
        self.fields["contenido"].widget.attrs.update({'class': 'campo__input', 'type':"textarea", 'placeholder':"Descripción"})
        self.fields["productos_disponibles"].widget.attrs.update({'class': 'campo_p-disponible', 'for':"disponibilidad"})
        self.fields["imagen"].widget.attrs.update({'class': 'campo_p-file', 'id':'file', "type":"file",'accept':'.jpg,.png'})
        
class CategoriasForm(forms.ModelForm):
    class Meta:
        model = Categorias
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(CategoriasForm, self).__init__(*args, **kwargs)
        self.fields["categoria"].widget.attrs.update({'class': 'campo__input', 'type':"text", 'placeholder':"Nombre de la categoria"})

class SearchForm(forms.Form):
    titulo = forms.CharField(max_length=30, required = False)
    ORDER_OPCIONES = (
        ("titulo", "Titulo"),
        ("Fecha",(
            ("antiguo", "Antiguo"),
            ("nuevo", "Nuevo"))
        ))
    orden = forms.ChoiceField(choices=ORDER_OPCIONES, required = False,
        initial="nuevo")

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        self.fields["titulo"].widget.attrs.update({"class":"buscador__campo", "type":"search", "placeholder":"Buscar", "aria-label":"Search"})

class CarritoForm(forms.ModelForm):
    class Meta:
        model = Carritos
        fields = ('cantidad',)

    def __init__(self, *args, **kwargs):
        super(CarritoForm, self).__init__(*args, **kwargs)
        self.fields["cantidad"].widget.attrs.update({'type':"number",'value':"{{'cantidad'}}",'class':"carrito__campo", 'id':"cantidad", 'name':"cantidad", 'min':'0'})

comercio_electronico/productos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout,login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from .forms import ProductosForm, SearchForm, CarritoForm, CategoriasForm
from .models import Productos, Categorias, Carritos
from usuario.models import Perfil
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import PasswordChangeForm
from django.core.paginator import Paginator
from django.utils import timezone
from django.contrib.auth.models import  User

#@login_required
def crear_producto(request):
	#BUSQUEDA--------------------------------------------------------------------------------------------------------
	if request.GET:
		search_form = SearchForm(request.GET)
	else:
		search_form = SearchForm()
	#FIN BUSQUEDA-----------------------------------------------------------------------------------------------------
	
	#CREAR PRODUCTO---------------------------------------------------------------------------------------------------
	if request.method == "POST":
		form= ProductosForm(request.POST,request.FILES)
		if form.is_valid():
			producto=form.save(commit=False)
			producto.usuario = request.user
			producto.save()
			return redirect('index')
		else:
			contexto={"form":form,
			}
			return render(request, "productos/agregar_productos.html",contexto)
	form = ProductosForm()

	lista_productos = Productos.objects.all()[0:16]
	lista_categorias = Categorias.objects.all()

	contexto={"form":form,
			"search_form":search_form,
			"lista_categorias": lista_categorias,
			'lista_productos': lista_productos,
			}
	return render(request, "productos/agregar_productos.html",contexto)

#@login_required
def borrarProducto(request, id):
  	producto = get_object_or_404(Productos, id=id)
  	producto.delete()
  	return redirect("index")
  	
#@login_required
def editar_producto(request, id):
	#BUSQUEDA--------------------------------------------------------------------------------------------------------
	if request.GET:
		search_form = SearchForm(request.GET)
	else:
		search_form = SearchForm()
	#FIN BUSQUEDA-----------------------------------------------------------------------------------------------------
	producto = get_object_or_404(Productos, id=id)
	if request.method == "POST":
		user = Perfil.objects.get(username=request.user)
		producto.usuario = user
		form = ProductosForm(data=request.POST, files=request.FILES, instance=producto)
		if form.is_valid():
			form.save()
			return redirect("index")
	else:
		form = ProductosForm(instance = producto)
		return render(request, 'productos/editar_producto.html', {
			"producto": producto,
			"form": form,
        })

def search(request):
	if request.GET:
		search_form = SearchForm(request.GET)
	else:
		search_form = SearchForm()

	filtro_titulo = request.GET.get("titulo", "")
	orden_post = request.GET.get("orden", None)
	lista_productos = Productos.objects.filter(titulo__icontains = filtro_titulo)

	if orden_post == "titulo":
		lista_productos= lista_productos.order_by("titulo")
	elif orden_post == "antiguo":
		lista_productos= lista_productos.order_by("fecha_creacion")
	elif orden_post == "nuevo":
		lista_productos= lista_productos.order_by("-fecha_creacion")

	#paginate
	
	paginate = Paginator(lista_productos, 12)
	page_number = request.GET.get('page')
	page_obj = paginate.get_page(page_number)

	form = SearchForm()
	lista_categorias = Categorias.objects.all()		
	contexto = { "form":form,
				 "lista_productos":lista_productos,
				 "search_form":search_form,
				 "lista_categorias": lista_categorias,
				 "page_obj" : page_obj,
				 }
	return render(request, "productos/search.html",contexto)

def agregar_categoria(request):
	if request.method == "POST":
		form= CategoriasForm(request.POST,request.FILES)
		if form.is_valid():
			categoria=form.save(commit=False)
			categoria.usuario = request.user
			categoria.save()
		else:
			contexto={"form":form,
				#	"search_form":search_form,
			}
			return render(request, "productos/agregar_categorias.html",contexto)
	form = CategoriasForm()
	lista_categorias = Categorias.objects.all()
	categoria : Categorias.objects.all()
	contexto={"form":form,
				"lista_categorias": lista_categorias,
		#	"search_form":search_form,
			}
	return render(request, "productos/agregar_categorias.html",contexto)

def filtro_categoria(request, id):
    categoria = get_object_or_404(Categorias, id=id)
    queryset = Productos.objects.all()
    queryset = queryset.filter(categoria=categoria)
    lista_categorias = Categorias.objects.all()
    contexto = {
        "lista_productos": queryset,
        "lista_categorias": lista_categorias,
        "categoria_seleccionada": categoria,
        }
    return render(request,"index.html", contexto)

def editar_categoria(request, id):
	categoria = get_object_or_404(Categorias, id=id)
	if request.method == "POST":
		user = Perfil.objects.get(username=request.user)
		categoria.usuario = user
		form = CategoriasForm(data=request.POST, files=request.FILES, instance=categoria)
		if form.is_valid():
			form.save()
			return redirect("productos:agregar_categoria")
	else:
		form = CategoriasForm(instance = categoria)
		return render(request, 'productos/editar_categoria.html', {
            "categoria": categoria,
            "form": form
        })

def borrar_categoria(request, id):
  	categoria = get_object_or_404(Categorias, id=id)
  	categoria.delete()
  	return redirect("productos:agregar_categoria")

#@login_required
def carrito(request):
	#BUSQUEDA--------------------------------------------------------------------------------------------------------
#	if request.GET:
#		search_form = SearchForm(request.GET)
#	else:
#		search_form = SearchForm()
	
	#FIN BUSQUEDA-----------------------------------------------------------------------------------------------------
	
	carritos = Carritos.objects.all()
	
	#total de productos
	total= 0
	total_cantidad = 0
	for x in carritos:
		total+= int(x.producto.precio_oferta)
		total*= int(x.cantidad)
		total_cantidad += int(x.cantidad)
		form = CarritoForm()


	#modificar cantidad de productos en el carrito
	lista_categorias = Categorias.objects.all()
	form = CarritoForm()
	contexto ={
#    "search_form":search_form,
	'carritos':carritos,
	
	'total':total,
	'total_cantidad':total_cantidad,
	'form_carrito':form,
	"lista_categorias": lista_categorias,
    }
	return render(request,"carritos/carritos.html", contexto)

#@login_required
def agregarCarrito(request, id):
#	if request.GET:
#		search_form = SearchForm(request.GET)
#	else:
#		search_form = SearchForm()
	#FIN BUSQUEDA-----------------------------------------------------------------------------------------------------
	
	#agregar carrito----------------------------------------------------------------------------------------------------
	producto = Productos.objects.get(pk=id)

	if request.method == "POST":
		form = CarritoForm(request.POST)		
		user = Perfil.objects.get(username=request.user)
		if form.is_valid():
			carrito = form.save(commit=False)
			carrito.usuario = request.user
			carrito.producto = producto
			carrito.save()
			return redirect('index')

	return redirect('index')



@login_required
def borrar_carrito(request, id):
	carrito = get_object_or_404(Carritos, id=id)
	carrito.delete()
	return redirect("index")
@login_required
def editar_carrito(request, id):
    carrito = get_object_or_404(Carritos, id=id)
    if request.method == "POST":  
        user = Perfil.objects.get(username=request.user)   
        carrito.usuario = user
        form = CarritoForm(data=request.POST, files=request.FILES, instance=carrito)
        if form.is_valid():
            form.save()
            return redirect("productos:carrito")
    else:
        form = CarritoForm(instance = carrito)
        return render(request, 'carritos/carritos.html', {
            "carrito": carrito,
            "form": form
        })

def search(request):
	form = SearchForm()
	if request.GET:
		search_form = SearchForm(request.GET)
	else:
		search_form = SearchForm()
	# parametros
	param_titulo = request.GET.get('titulo','')
	# filtrar titulo
	lista_productos = Productos.objects.filter(titulo__contains=param_titulo)
	
	
#	forms = AuthenticationForm()
#	if request.method == "POST":
#		forms = AuthenticationForm(data=request.POST)
#		if forms.is_valid():
#			username = forms.cleaned_data["username"]
#			password = forms.cleaned_data["password"]
#			user = authenticate(username=username, password=password)
#			if user is not None:
#				login(request, user)
#				return redirect("bienvenido")
	contexto = {"form":form,
	     		"lista_productos":lista_productos,
				"search_form":search_form,
				
				 }
	return render(request, "productos/search.html",contexto)

comercio_electronico/productos/templates/productos/agregar_categorias.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<main class="contenido-principal">
	<div class="mensaje-publicitario">
		<h3 class="mensaje-publicitario__titulo centrar-text">La mejor tienda de Gral. San Martín</h3>
	</div>

	{% include 'navbar.html' %}
	<div class="contenedor">
		<section class="configuraciones-generales">
			<h2 class="ajuste__titulo">Ajustes Generales</h2>
			<div class="barra-configuracion"></div>
				<nav class="configuracion__opciones">
					<a class="configuracion__opciones__link" href="add_categorias.html">Agregar Categoria</a>
					<a class="configuracion__opciones__link active" href="{% url 'productos:crear_producto' %}">Agregar Producto</a>
				</nav>
				<form class="categorias-campos" method="POST" enctype="multipart/form-data" action="{% url 'productos:agregar_categoria' %}">
					{% csrf_token %}
					<fieldset>
						<legend class="categorias-campos__titulo">Agregar categoria</legend>
						<div class="campos-add">
							<div class="campo">
								{{ form.categoria }}{{ form.categoria.errors }}
							</div>
							<input type="submit" value="Agregar" class="formulario__btn">
						</div>
					</fieldset>					
				</form>
					<fieldset>
						<legend class="categorias-campos__titulo">Categorias existentes</legend>
						<div class="categotias-existentes">
							{% for categoria in lista_categorias %}
							<div class="campo__categoria">
								<span class="campo__categoria__nombre">{{ categoria }}</span>
								<a href="{% url 'productos:editar_categoria' categoria.id %}" class="formulario__btn">Editar Categoria</a>
        						<a href="{% url 'productos:borrar_categoria' categoria.id %}" class="formulario__btn">Borrar Categoria</a>
							</div>{% endfor %}
						</div>
					</fieldset>
			</section>
			
		</div>
{% include 'footer.html' %}
	<!--scripts de Jorge-->
	<script src="{% static 'js/app.js' %}"></script>
	<!--scripts Carrito-->
	<script type="text/javascript" src="{% static 'js/carrito.js' %}"></script>
	<!--scripts de bootstrp-->
	<script src="https://kit.fontawesome.com/1356b06277.js" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>

</main>
{% endblock %}

comercio_electronico/productos/templates/productos/agregar_productos.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<main class="contenido-principal">
	<div class="mensaje-publicitario">
		<h3 class="mensaje-publicitario__titulo centrar-text">La mejor tienda de Gral. San Martín</h3>
	</div>

	{% include 'navbar.html' %}
	<div class="contenedor">
		<section class="configuraciones-generales">
			<h2 class="ajuste__titulo">Ajustes Generales</h2>
			<div class="barra-configuracion"></div>
				<nav class="configuracion__opciones">
					<a class="configuracion__opciones__link" href="add_categorias.html">Agregar Categoria</a>
					<a class="configuracion__opciones__link active" href="{% url 'productos:crear_producto' %}">Agregar Producto</a>
				</nav>
				<div class="agregar-productos">
					<form method="POST" enctype="multipart/form-data" action="{% url 'productos:crear_producto' %}">
						<fieldset>
						<legend>Agregar Producto</legend>
						<div class="campos-productos">
						{% csrf_token %}
							<div class="campo_p">
							 {{ form.titulo }}{{ form.titulo.errors }}
							</div>
							<div class="campo_p">
								{{ form.categoria }} {{ form.categoria.errors }}
							</div>
							<div class="campo_p">
								{{ form.contenido }}{{ form.contenido.errors }}
							</div>
							<div class="campo_p">
								{{form.precio}} {{form.precio.errors}}
							</div>
							<div class="campo_p">
								{{form.precio_oferta}} {{form.precio_oferta.errors}}
							</div>
							<div class="campo_p">
								{{ form.productos_disponibles }}{{ form.productos_disponibles.errors }}
							
							</div>
							<div class="campo_p">
								<label for="file" class="formulario__btn">Agregar imágen</label>
								{{ form.imagen }} {{ form.imagen.errors }}
							</div>
						</div>
						<div class="campo_p">
								<input type="submit" class="formulario__btn" value="Agregar producto">
							</div>
					</fieldset>
					</form>
					<div class="productos-existentes">
						<fieldset>
							<legend>Productos Agregados</legend>
							
							<div class="productos-division">
								{% for prod in lista_productos %}
								<div class="producto__existente">
								<img class="producto__existente-img" src="{{ prod.imagen.url }}" alt="producto">
								<div class="producto__existente-informacion">
									<span class="nombre">{{prod.titulo}}</span>
									<span class="nombre">{{prod.contenido | truncatechars:30 }}</span>
									<span class="precio">${{prod.precio}}</span>
									<span class="producto__existente-disponible">${{ prod.precio_oferta }}</span>
									{% if productos.productos_disponibles %}
									<span class="nombre">Disponible</span>
									{% else %}
									<span class="producto__existente-disponible">Disponible</span>
									{% endif%}
									<a href="{% url 'productos:editar_producto' prod.id %}" class="formulario__btn">Editar Producto</a>
        							<a href="{% url 'productos:borrarProducto' prod.id %}" class="formulario__btn">Borrar Producto</a>
								</div>
							</div>
							{% endfor %}
							</div>
							
						</fieldset>
					</div>
				</div>
		</section>
	</div>
	{% include 'footer.html' %}
	<!--scripts de Jorge-->
	<script src="{% static 'js/app.js' %}"></script>
	<!--scripts Carrito-->
	<script type="text/javascript" src="{% static 'js/carrito.js' %}"></script>
	<!--scripts de bootstrp-->
	<script src="https://kit.fontawesome.com/1356b06277.js" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>

</main>
{% endblock %}

comercio_electronico/productos/templates/productos/card_productos.html
{% for productos in lista_productos %}
<article class="producto">
	<img class="producto__imagen" src="{{ productos.imagen.url }}" alt="producto">
	<div class="nombre-precios">
		<span class="nombre">{{productos.titulo}}</span>
		<span class="nombre">{{productos.contenido | truncatechars:30 }}</span>
		<span class="precio">${{productos.precio}}</span>
		<span class="producto__existente-disponible">${{ productos.precio_oferta }}</span>
		{% if productos.productos_disponibles %}
		<span class="nombre">Disponible</span>
		{% else %}
		<span class="producto__existente-disponible">Disponible</span>
		{% endif%}
		
	</div>
	<!-- <a class="producto__comprar" href="#">Agregar producto</a> -->
	<form method="POST" action="{% url 'productos:agregarCarrito' productos.id%}" enctype="multipart/form-data">
	         {% csrf_token %}         
	         {{form_carrito}}
	    	<input onclick="agregar()" type="submit" class="producto__comprar" value="Agregar al Carrito">     
	</form>

<!--
{#{% if request.user == producto.usuario %}#}	
        <a href="{% url 'productos:editar_producto' productos.id %}" class="formulario__btn">Editar Producto</a>
        <a href="{% url 'productos:borrarProducto' productos.id %}" class="formulario__btn">Borrar Producto</a>
 {#  {% endif %}#} -->
</article>
<script type="text/javascript">

const producto = document.querySelector(".body");
function agregar() {
	const add = document.createElement("SPAN");
	add.textContent = "El producto se agrego correctamente";
	add.classList.add("exito");
	producto.appendChild(add);
	console.log(add);

	setTimeout(() => {
		add.remove();
	}, 800)
	
}


</script>
{% endfor %}

comercio_electronico/productos/templates/productos/editar_categoria.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<main class="contenido-principal">
	<div class="mensaje-publicitario">
		<h3 class="mensaje-publicitario__titulo centrar-text">La mejor tienda de Gral. San Martín</h3>
	</div>

	{% include 'navbar.html' %}
	<div class="contenedor">
		<section class="configuraciones-generales">
			<h2 class="ajuste__titulo">Ajustes Generales</h2>
			<div class="barra-configuracion"></div>
				<nav class="configuracion__opciones">
					<a class="configuracion__opciones__link" href="add_categorias.html">Agregar Categoria</a>
					<a class="configuracion__opciones__link active" href="{% url 'productos:crear_producto' %}">Agregar Producto</a>
				</nav>
				<form class="categorias-campos" method="POST">
					{% csrf_token %}
					<fieldset>
						<legend class="categorias-campos__titulo">Editar categoria</legend>
						<div class="campos-add">
							<div class="campo">
								{{ form.categoria }}{{ form.categoria.errors }}
							</div>
							<input type="submit" value="Guardar" class="formulario__btn">
						</div>
					</fieldset>					
				</form>
					
			</section>
			
		</div>
{% include 'footer.html' %}
	<!--scripts de Jorge-->
	<script src="{% static 'js/app.js' %}"></script>
	<!--scripts Carrito-->
	<script type="text/javascript" src="{% static 'js/carrito.js' %}"></script>
	<!--scripts de bootstrp-->
	<script src="https://kit.fontawesome.com/1356b06277.js" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>

</main>
{% endblock %}

comercio_electronico/productos/templates/productos/editar_producto.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<main class="contenido-principal">
	<div class="mensaje-publicitario">
		<h3 class="mensaje-publicitario__titulo centrar-text">La mejor tienda de Gral. San Martín</h3>
	</div>

	{% include 'navbar.html' %}
	<div class="contenedor">
		<section class="configuraciones-generales">
			<h2 class="ajuste__titulo">Ajustes Generales</h2>
			<div class="barra-configuracion"></div>
				<nav class="configuracion__opciones">
					<a class="configuracion__opciones__link" href="add_categorias.html">Agregar Categoria</a>
					<a class="configuracion__opciones__link active" href="{% url 'productos:crear_producto' %}">Agregar Producto</a>
				</nav>
				<div class="agregar-productos">
					<form method="POST">
						<fieldset>
						<legend>Agregar Producto</legend>
						<div class="campos-productos">
						{% csrf_token %}
							<div class="campo_p">
							 {{ form.titulo }}{{ form.titulo.errors }}
							</div>
							<div class="campo_p">
								{{ form.categoria }} {{ form.categoria.errors }}
							</div>
							<div class="campo_p">
								{{ form.contenido }}{{ form.contenido.errors }}
							</div>
							<div class="campo_p">
								{{form.precio}} {{form.precio.errors}}
							</div>
							<div class="campo_p">
								{{form.precio_oferta}} {{form.precio_oferta.errors}}
							</div>
							<div class="campo_p">
								{{ form.productos_disponibles }}{{ form.productos_disponibles.errors }}
							
							</div>
							<div class="campo_p">
								<label for="file" class="formulario__btn">Agregar imágen</label>
								{{ form.imagen }} {{ form.imagen.errors }}
							</div>
						</div>
						<div class="campo_p">
								<input type="submit" class="formulario__btn" value="Guardar">
							</div>
					</fieldset>
					</form>
					<div class="productos-existentes">
						<fieldset>
							<legend>Productos Agregados</legend>
							<div class="productos-division">
								<div class="producto__existente">
								<img class="producto__existente-img" src="img/fideos01.png" alt="">
								<div class="producto__existente-informacion">
									<span class="producto__existente-nombre">Fideo Molto</span>
									<span class="producto__existente-precio">$35</span>
									<span class="producto__existente-disponible">Disponible</span>
									<a class="formulario__btn" href="#">Eliminar</a>
								</div>
							</div>
							</div>
						</fieldset>
					</div>
				</div>
		</section>
	</div>
	{% include 'footer.html' %}
	<!--scripts de Jorge-->
	<script src="{% static 'js/app.js' %}"></script>
	<!--scripts Carrito-->
	<script type="text/javascript" src="{% static 'js/carrito.js' %}"></script>
	<!--scripts de bootstrp-->
	<script src="https://kit.fontawesome.com/1356b06277.js" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>

</main>
{% endblock %}

comercio_electronico/productos/templates/productos/search.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

{% block contenido %}
<form action="" >
{{ form }}
<button class="formulario__btn" type="submit">Buscar</button> 
</form>

<h1>Resultado</h1>
<hr>
<div><h2>Productos</h2>
<div class="contenedor">
{% include 'productos/card_productos.html' with lista_productos=lista_productos %}
</div>
</div>
{% endblock %}
{% endblock %}

comercio_electronico/productos/templates/productos/search_form.html
<div class="buscador flex-align">
	<form method="GET" action="{% url 'productos:search' %}">
		{{ search_form.titulo }}	
	</form>
	<i class="fas fa-search buscador__icon"></i>
</div>